### ISSUE TITLE
ROC support

### ISSUE THREAD

**Issue by barucden** [JuliaML/LIBSVM.jl#61]
Hi,

I believe we have no support for computing ROC, yet. Would you, @mpastell, be interested in having something in that direction implemented? 

I have implemented a function for computing TPRs and FPRs (and AUC), and I am happy to share it if you'd like me to.

**Comment by iblis17** [comment]
hmm, I'm not sure your implement is strongly related to SVM or not.
Is that something should be put in the [LearnBase.jl](https://github.com/JuliaML/LearnBase.jl) ?

**Comment by barucden** [comment]
I am not sure either :smile: 

There is a feature for computing ROC in [MLBase.jl](https://mlbasejl.readthedocs.io/en/latest/perfeval.html#computing-roc-curves) but it seems too complicated. I implemented just a single function to produce a vector of TPRs and FPRs, which can be directly used to plot the ROC curve. Since I only ever used this function for SVMs, I thought it might be desirable to have it here too.

But it's completely understandable if you feel like it does not belong here. After all, this issue hasn't gain any attention, which shows that the community does not strive for it.

**Comment by iblis17** [comment]
hmm, I tend not to put ROC stuffs in this repo. Maybe your scripts can be contributed to MJL or MLBase.

**Comment by barucden** [comment]
Understood. I am closing this issue.
