### ISSUE TITLE
Read datasets from libsvm

### ISSUE THREAD

**Issue by matthiasbe** [JuliaML/LIBSVM.jl#93]
Is it possible to read datasets from [libsvm webpage](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/) in Julia ?

Here is an example of data (text file)

```
751.0 5:1 8:0.0 10:0.652913 11:0.701456 12:0.682039 13:0.677184 14:0.599515 15:0.589806 16:0.631068
703.0 6:1 8:0.0 10:0.696601941748 11:0.652913 12:0.701456 13:0.682039 14:0.677184 15:0.599515 16:0.589806
677.0 8:0.0 10:0.580097087379 11:0.696601941748 12:0.652913 13:0.701456 14:0.682039 15:0.677184 16:0.599515
718.0 1:1 8:0.0 10:0.516990291262 11:0.580097087379 12:0.696601941748 13:0.652913 14:0.701456 15:0.682039 16:0.677184
```

I couldn't find a direct way using CSV.jl or LIBSVM.jl, did I miss something ?

Thank you
Matthias

**Comment by ablaom** [comment]
I don't know. I'm pretty sure LIBSVM.jl does not provide that functionality.

Some Julia grabbers for ML/states data sets include RDatasets.jl, OpenML.jl. And there is MLDatasets, which is focused on deep learning applications.
